name: keep-alive

on:
  schedule:
    # every 10 hours: at minute 0 of hours 0,10,20
    - cron: '0 0,10,20 * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl keep-alive URL
        run: |
          set -euo pipefail
          URL="https://justpark-earnings.streamlit.app/"
          echo "GET $URL"
          curl -fsS -o /dev/null -w "%{http_code}" "$URL" || true
